@host = http://localhost:5076

### Get all notes
GET {{host}}/api/notes
Accept: application/json

### Get one note by id
GET {{host}}/api/notes/1
Accept: application/json

### Create a note
POST {{host}}/api/notes
Content-Type: application/json

{
  "title": "keep sending  notes     and see what happens   ",
  "body": "This one should live in SQL Server"
}

### Delete a note by id
DELETE {{host}}/api/notes/1
